refactor! feat: Add aten::reflection_pad2d and aten::reflection_pad1 converter support.
NVIDIA/Torch-TensorRT pull request #831
Opened 2022-01-26 21:13 UTC by p1x31

Signed-off-by: Vadim Makarenkov <vadim_makarenkov@hotmail.co.uk>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Refactor of #611 for the 1.1.0a0+b652045d version
Add aten::reflection_pad2d and aten::reflection_pad1d support.
All credits to @chengyute 

Fixes #775 (full compilation) #545 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines of this project (You can use the linters)
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests to verify my fix or my feature
- [X] New and existing unit tests pass locally with my changes

2022-02-05 13:58 UTC, p1x31 commented
These converters only supported in [TensorRT 8.2.0.6 EA](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-2-0-EA) release

2022-02-08 17:54 UTC, narendasan commented
We are about to land 8.2 in master, will merge this after

2022-02-14 03:09 UTC, peri044 approved these changes
Please fix the linter issue. The code LGTM

2022-02-14 03:21 UTC, peri044 requested changes

2022-02-14 03:21 UTC, peri044 commented on tests/core/conversion/converters/test_reflection_pad.cpp
> +  auto params = torch_tensorrt::core::conversion::get_named_params(g->inputs(), {});
`get_named_params` is now replaced with `get_static_params`. Please change this and other similar lines with 
` params = torch_tensorrt::core::ir::get_static_params(g->inputs(), {});`

2022-02-24 12:27 UTC, closed without merging