Add remainders' op
NVIDIA/Torch-TensorRT pull request #901
Opened 2022-02-28 05:11 UTC by Njuapp

Signed-off-by: Cheng Hang <chang@nvidia.com>

# Description

Add support for `aten::remainder.Tensor(Tensor self, Tensor other) -> (Tensor)` and `aten::remainder.Scalar(Tensor self, Scalar other) -> (Tensor)`, which required by Video Swin Transformer.

Fixes #766

## Type of change

Please delete options that are not relevant and/or add your own.

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

2022-03-11 22:13 UTC, peri044 requested changes
Thanks for the contribution. Instead of a converter, we can implement this as a lowering pass. 
aten::remainder can be lowered to aten::floor_divide -> aten::mul -> aten::sub. We prefer lowering usually so that our converter library is minimal and compact
You can take a look at the existing lowering passes for example.

2022-03-18 06:56 UTC, chenghangNV commented
Hi, Peri, I have removed the coverters for remainder, and use lowering instead. Please check the changes.

2022-03-18 06:58 UTC, Njuapp commented
@peri044 Hi, I have committed new changes, where converters are replaced by lowering for aten::remainder. Please check the changes.

2022-03-18 18:16 UTC, peri044 requested changes
code LGTM. Please add one more test case which verifies numerical correctness of remainder op after lowering. 
Eg: https://github.com/NVIDIA/Torch-TensorRT/blob/master/tests/core/conversion/converters/test_activation.cpp#L205-L232
You can add this test case here https://github.com/NVIDIA/Torch-TensorRT/blob/master/tests/core/conversion/converters/test_element_wise.cpp

2022-03-21 05:23 UTC, Njuapp commented
> code LGTM. Please add one more test case which verifies numerical correctness of remainder op after lowering. Eg: https://github.com/NVIDIA/Torch-TensorRT/blob/master/tests/core/conversion/converters/test_activation.cpp#L205-L232 You can add this test case here https://github.com/NVIDIA/Torch-TensorRT/blob/master/tests/core/conversion/converters/test_element_wise.cpp

Hi Dheeraj, please check my newly added testcase which verifies the correctness of aten::remainder lowering. I run jit with original graph(w/o lowering), and then lowered the graph, at last run the trt engine with lowered graph.

2022-03-21 23:31 UTC, peri044 approved these changes

2022-03-21 23:33 UTC, peri044 commented
LGTM. Please sign your commits to ensure DCO passes (https://github.com/NVIDIA/Torch-TensorRT/pull/901/checks?check_run_id=5622412005)

2022-03-22 03:08 UTC, Njuapp commented
Hi @peri044, I have added sign-off-by line to every commits of mine by following instructions within that webpage:
1.`git rebase HEAD~7 --signoff`
2.`git push --force-with-lease origin aten_remainder`

2022-03-22 03:47 UTC, peri044 commented
Now the branch has conflicts. You probably have to rebase with master. Can you fix them ?

2022-03-23 07:55 UTC, Njuapp commented
@peri044 Hi Dheeraj, I have fixed those conflicts, and this PR still needs one more aproval to be merged.

2022-03-25 18:57 UTC, narendasan commented
Can you rebase this branch? Theres a lot of extra changes coming in

2022-04-01 04:04 UTC, Njuapp commented
@narendasan @peri044 Hi Naren and Dheeraj, please check new commits. I have cleaned previous redundant commits and now it only contains a single commit with sign-off.

2022-04-05 01:53 UTC, narendasan approved these changes
LGTM

2022-04-05 01:53 UTC, merged